### ISSUE TITLE
add alias to "latest"

### ISSUE THREAD

**Issue by yjbanov** [cbracken/dvm#1]
`dvm install latest` would install the latest stable SDK
`dvm install latest_dev` would install the latest dev SDK
`dvm use latest` would use the latest installed SDK
...

**Comment by cbracken** [comment]
`dvm install latest` should install or replace the latest version in a version-numbered directory.

Just added support for a `current` symlink. Will look at doing a `latest` as well.

**Comment by cbracken** [comment]
Update: `dvm install latest` works properly now.

With support for local `--path` SDKs now landed, creating and maintaining a `latest` symlink is very special-casey. Local SDK builds might have weird versions etc.

With alias support landed, the user now has the ability to manage aliases how they like. If you want to maintain a latest symlink, a thin wrapper shell script like this might work:

```
#!/bin/bash
dvm install latest
latest="$(find $DVM_ROOT/darts -maxdepth 1 ! -path $DVM_ROOT/darts -type d -exec basename {} \; | sort -V | tail -1)"
dvm alias delete latest
dvm alias create latest "$latest"
```
