### ISSUE TITLE
Update Readme dvm need uzip in system

### ISSUE THREAD

**Issue by adnanex** [cbracken/dvm#18]

**Comment by cbracken** [comment]
Thanks for filing! Out of curiosity, which Linux distribution are you running that doesn’t include `unzip` in the base install? Or is it that `unzip` is on the system but not in your `PATH`? If it’s the latter, it may be useful to add some checking for common paths.

**Comment by adnanex** [comment]
windows 10 WSL ubuntu 20.04

**Comment by cbracken** [comment]
Thanks. Fixed in #19.
