### ISSUE TITLE
can we use this sideby side with fvm?

### ISSUE THREAD

**Issue by codeitlikemiley** [cbracken/dvm#34]
Does the package install here also resonate with dart version folder?
Im currenly only using fvm , is it advisable to use both?
:)

**Comment by cbracken** [comment]
I'm unfamiliar with `fvm` -- I assume Flutter version manager. If so, then I don't think there's too much on an advantage to using `dvm` if your primary development toolchain is Flutter. Flutter and Dart releases are now paired on a common schedule, so you can always switch Flutter version to pick up the related Dart toolchain.

From a pedantic point of view, it's worth noting that the Dart SDK bundled with Flutter is not the identical binaries that ship in the Dart SDK download. You'll notice this if you run `dart --version`. However, the difference is pretty close to negligible at this point -- the Dart SDK we ship with Flutter is built as part of the Flutter engine build process from the same sources using the same build rules.
