### ISSUE TITLE
Custom $DVM_ROOT?

### ISSUE THREAD

**Issue by are** [cbracken/dvm#37]
Because `dvm` overwrites the `$DVM_ROOT` variable, it isn't possible to specify a different installation location.

Would it be enough to do this conditionally instead (if `$DVM_ROOT` is not defined, set it as `$HOME/.dvm`)?

**Comment by cbracken** [comment]
Sounds like a great idea; apologies for not having had this feature since the beginning!

**Comment by cbracken** [comment]
Merged in #38. Thank you!
